export const PLAYER_CONTROLS_MIN_HEIGHT = 80
export const SNAP_POINT_THRESHOLD_POINT = 100
export const VIDEO_WIDTH_CHANGE_HEIGHT_DELTA = 50

export const TAB_BAR_MAX_HEIGHT = 80
export const TAB_BAR_TOP_PADDING = 10
export const TAB_BAR_BORDER_TOP_WIDTH = 1
